apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrepo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myrepo
  template:
    metadata:
      labels:
        app: myrepo
    spec:
      imagePullSecrets:
        - name: myrepo-secret  # Reference the secret you created
      containers:
        - name: myrepo-container
          image: trishanetrx/myrepo:latest  # Use your Docker image here
          ports:
            - containerPort: 80

