apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  mariadb-root-password: cm9vdHBhc3N3b3Jk # "rootpassword" in Base64
  mariadb-password: dXNlcnBhc3N3b3Jk # "userpassword" in Base64
  mariadb-database: d29yZHByZXNz # "wordpress" in Base64
  mariadb-user: dXNlcg== # "user" in Base64

