apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myrepo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/yourusername/aks-cluster-deploy.git  # Your Git repo
    targetRevision: main
    path: .  # Root directory, adjust if your manifests are in a subfolder
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

