apiVersion: v1
kind: Service
metadata:
  name: myrepo-service
  namespace: default
spec:
  selector:
    app: myrepo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Adjust to LoadBalancer if you need external access

